Фух
beast666tm/J2_netChat pull request #3
Opened 2021-12-02 20:41 UTC by beast666tm

Оооочень сложная задача!

2021-12-02 20:46 UTC, beast666tm reviewed
Постараюсь потом почистить лишнее! Надеюсь разберетесь

2021-12-03 05:41 UTC, efserg requested changes

2021-12-03 05:41 UTC, efserg commented on src/main/java/ru/gb/server/JdbcApp.java
> +        String query = String.format("select nick from users where login = '%s' and password = '%s'",
Такое не принимаю. Исправляйте на PreparedStatement, чтобы не было возможности для sql-injection

2021-12-03 06:53 UTC, beast666tm commented on src/main/java/ru/gb/server/JdbcApp.java
> +        String query = String.format("select nick from users where login = '%s' and password = '%s'",
Так вот же этот метод! Я же писал что от мусора позже избавлюсь!

2021-12-03 06:53 UTC, beast666tm commented on src/main/java/ru/gb/server/JdbcApp.java
> +        String query = String.format("select nick from users where login = '%s' and password = '%s'",
public static String getUserNickname(String login, String password) {
        String nick = null;
        try {
            getUserNicknameStatement.setString(1, login);
            getUserNicknameStatement.setString(2, password);
            ResultSet rs = getUserNicknameStatement.executeQuery();
            if (rs.next()) {
                nick = rs.getString(1);
            }
            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return nick;
    }

2021-12-03 06:54 UTC, beast666tm commented on src/main/java/ru/gb/server/JdbcApp.java
> +        String query = String.format("select nick from users where login = '%s' and password = '%s'",
synchronized static String getNickname()... Метод в коде вообще не действующий закомментировать забыл просто!

2021-12-03 09:10 UTC, efserg commented on src/main/java/ru/gb/server/JdbcApp.java
> +        String query = String.format("select nick from users where login = '%s' and password = '%s'",
Не надо в готовом пулл-реквесте оставлять неиспользуемый или закомментированный код. Перед отправкой д/з все проверяйте

2021-12-03 09:48 UTC, beast666tm commented on src/main/java/ru/gb/server/JdbcApp.java
> +        String query = String.format("select nick from users where login = '%s' and password = '%s'",
Ок просто отправлял в запаре! Не думаю что успею с историей чата

2021-12-03 11:11 UTC, merged

2021-12-03 11:11 UTC, beast666tm commented
Слияние